config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'categories/index'

  get 'categories/show'

  get 'categories/update'

  get 'categories/destroy'

  get 'categories/new'

  get 'categories/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  get '/news', to: 'pages#news'

  get '/front', to: 'pages#front'

  get '/back', to: 'pages#back'

  get '/real', to: 'pages#real' 

  resources :posts
  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  include Sluggable

  has_many :posts
  validates :title, presence: { message: 'ne doit pas etre vide'}
  validates :title, uniqueness: { message: 'existe deja dans la base de donnees'}

end

app/models/concerns/sluggable.rb
module Sluggable

extend ActiveSupport::Concern

included do
  before_validation :set_default_slug, on: [:create, :update], if:'!slug.nil?'

  	private

  	def set_default_slug
  		if !self.title.nil? && !self.title.empty? && (self.slug.nil? || self.slug.empty?)
  			self.slug = title.parameterize
  		end
  	end

end

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	include Sluggable
	belongs_to :category, optional:true
	validates :title, presence: { message: 'ne doit pas etre vide'}
	validates :title, uniqueness: { message: 'existe deja dans la base de donnees'}

	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_category, only: [:show, :update, :destroy, :edit]

  def index
    @session = session[:user_id]
    @categories = Category.all
  end

  def show
  end

  def update
    @category.update(category_params)
    redirect_to categories_path
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path
  end

  def edit

  end

  private

  def category_params
    params.require(:category).permit(:title, :slug)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def real
	end	

	def news
	end

	def back
	end

	def front
	end
	
	def home
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:update, :edit, :show, :destroy]

  def index
  	@posts = Post.includes(:category).all
  end

  def show
  end

  def edit
  end

  def new
  	@post = current_user.posts.build
  end

  def update
  	if @post.update(post_params)
  	  redirect_to posts_path, success: "Article modifié avec succès"
    else
      render 'edit'
    end
  end

  def create
  	post = current_user.posts.build(post_params)
    if post.valid?
      post.save
  	  redirect_to post_path(post.id), success: "Article créer avec succès"
    else
      @post = post
      render 'new'
    end
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path, success: "Article supprimé avec succès"
  end
  private

  def post_params
  	params.require(:post).permit(:title, :content, :slug, :image, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Editer la catégorie</h1>

<%= form_for @category do |f| %>
<div class="form-group">
	<%= f.text_field :title, placeholder: 'Nom', class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.text_field :slug, placeholder: 'Url', class: 'form-control' %>
</div>

<div class="form-group">
	<button class="btn btn-primary" type="submit">Modifier la catégorie</button>
</div>

<% end %>

app/views/categories/index.html.erb
<h1>Les catégories</h1>

<table class="table">
	<thead>
	<tr>
		<td>ID</td>
		<td>Nom</td>
		<td>Action</td>
	</tr>
	</thead>
	<tbody>
		<% @categories.each do |category| %>
		<tr>
			<td><%= category.id %></td>
			<td><%= category.title %></td>
			<td><a href="<%= edit_category_path(category.id) %>" class="btn btn-primary">Editer</a>
			<a href="<%= category_path(category.id) %>" class="btn btn-danger" data-confirm="Etes-vous certain?" data-method="DELETE">Supprimer</a>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<p>
	<a href="<%= new_category_path %>" class="btn btn-success">Créer une nouvelle categorie</a>
</p>

app/views/categories/new.html.erb
<h1>Nouvelle catégorie</h1>

<%= form_for @category do |f| %>
<div class="form-group">
	<%= f.text_field :title, placeholder: 'Nom', class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.text_field :slug, placeholder: 'Url', class: 'form-control' %>
</div>

<div class="form-group">
	<button class="btn btn-primary" type="submit">Créer la catégorie</button>
</div>

<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>
  <body>
  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
  	<a class="navbar-brand" href="<%= root_path %>">Ruby on Rails</a>
  	<ul class="nav navbar-nav">
	  	<li class="nav-item">
        <a class="nav-link" href="<%= posts_path %>">Articles</a>
        <a class="nav-link" href="<%= categories_path %>">Catégories</a>
      <!--  <a class="nav-link" href="<%= news_path %>">News</a>
        <a class="nav-link" href="<%= front_path %>">Front-End</a>
        <a class="nav-link" href="<%= back_path %>">Back-End</a>
	  		<a class="nav-link" href="<%= real_path %>">Réalisation</a> -->
	  	</li>
  	</ul>
  </nav>
  <% if current_user %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Sign Up", new_user_registration_path %>
  <%= link_to "Sign In", new_user_session_path %>
  <% end %>
  
  <div class="container" style="padding-top: 5rem;">

  <% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>"><%= msg %></div>
  <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/back.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Back End</title>
</head>
<body>
<h1>Back End</h1>
</body>
</html>

app/views/pages/front.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Réalisation</title>
</head>
<body>
<h1>Front End</h1>
</body>
</html>

app/views/pages/home.html.erb
<h1>Bienvenue sur le site</h1>

app/views/pages/news.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>News</title>
</head>
<body>
<h1>News</h1>
</body>
</html>

app/views/pages/real.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Réalisation</title>
</head>
<body>
<h1>Réalisation</h1>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Editer l'article</h1>

<% if @post.errors.any? %>
	<div class="alert alert-danger">
		<% @post.errors.full_messages.each do |message| %>
			<%= message %>
	    <% end %>
	</div>
<% end %>

<%= form_for @post, html: {multipart:true} do |f| %>

	<div class="form-group">
	<label>Image de l'article</label>
	<%= f.file_field :image %>
	<div>

	<div class="form-group">
	<label>Titre de l'article</label>
	<%= f.text_field :title, class: 'form-control' %>
	<div>

<%= form_for @post do |f| %>
	<div class="form-group">
	<label>URL de l'article</label>
	<%= f.text_field :slug, class: 'form-control' %>
	<div>

	<div class="form-group">
	<label>Contenu de l'article</label>
	<%= f.text_area :content, class: 'form-control' %>
	<div>

	<div class="form-group">
	<label>Id de la catégorie</label>
	<%= f.text_area :category_id, class: 'form-control' %>


	<div class="form-group">
	<button type="submit" class="btn btn-primary">Modifier l'article</button>
	<div>
<% end %>
<% end %>

app/views/posts/index.html.erb
<h1>Articles</h1>

<% @posts.each do |post| %>
  <h2><%= image_tag post.image.url(:thumb) %></h2>
	<h2><%= post.title %></h2>
	<p><%= post.content %></p>

	<% if post.category %>
	<p>
		Categorie : <%= post.category.title %>
	</p>
	<% end %>
	<p>
	<a href="<%= post_path(post.id) %>" class="btn btn-primary">Lire la suite</a>
  <% if post.user == current_user %>
	<a href="<%= edit_post_path(post.id) %>" class="btn btn-default">Editer l'article</a>
	<a href="<%= post_path(post.id) %>" class="btn btn-danger" data-method="DELETE" data-confirm="Etes-vous certain?"> Supprimer</a>
  <% end %>
	</p>
<% end %>

  <% if current_user %>
  <p>
    <a href="<%= new_post_path %>" class="btn btn-success"> Créer un article</a>
  </p>
  <% end %>

app/views/posts/new.html.erb
<h1>Creer l'article</h1>

<% if @post.errors.any? %>
	<div class="alert alert-danger">
		<% @post.errors.full_messages.each do |message| %>
			<%= message %>
	    <% end %>
	</div>
<% end %>

<%= form_for @post, html: {multipart:true} do |f| %>

	<div class="form-group">
	<label>Image de l'article</label>
	<%= f.file_field :image %>
	<div>

	<div class="form-group">
	<label>Titre de l'article</label>
	<%= f.text_field :title, class: 'form-control' %>
	<div>

	<div class="form-group">
	<label>Contenu de l'article</label>
	<%= f.text_area :content, class: 'form-control' %>
	<div>

	<div class="form-group">
	<label>Id de la categorie</label>
	<%= f.text_field :category_id, class: 'form-control' %>
	<div>

	<div class="form-group">
	<button type="submit" class="btn btn-primary">Créer l'article</button>
	<div>
<% end %>

app/views/posts/show.html.erb
<h1><%= image_tag @post.image.url(:thumb) %></h1>

<h1><%= @post.title %></h1>

<p> <%= @post.content %></p>

<p>
	<a href="<%= posts_path %>" classe="btn btn-primary">Revenir aux articles</a>
</p>